# The name of the workflow
name: Pytest

# Specifies the trigger for our workflow
on: [push, pull_request]

jobs:
    test:
        
      # Creates environment/vm using the latest version of Ubuntu
      runs-on: ubuntu-latest

      steps:
        # An action that checks out our repository into the environment
        - uses: actions/checkout@v4

        # Sets up Python in our environment
        - name: Set Up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        
        - name: Install dependencies
          # How we can run command line commands
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -U pytest
            pip install -e .

        # Running Pytest!
        - name: Test with pytest
          run: |
            python -m pytest
